export const CODES = {
  METAL_MINE: 1,
  CRYSTAL_MINE: 2,
  DEUTERIUM_SYNTHETIZER: 3,
  SOLAR_PLANT: 4,
  FUSION_REACTOR: 12,
  METAL_STORAGE: 22,
  CRYSTAL_STORAGE: 23,
  DEUTERIUM_TANK: 24,
  SOLAR_SATELLITE: 212,
}

export default CODES;
